[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "scheduling_util"
description="Python utilities for scheduling tasks in long-running processes, such as backups and health checks. "
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "click==8.*",
    "click_pendulum==0.*",
    "coloredlogs==15.*",
    "hcio_client==1.*,>=1.0.1",
    "ordered_set==4.*",
    "pendulum==3.*",
    "pydantic==2.*",
    "requests==2.*",
    "run_with_logger==1.*",
]
authors = [
    {name = "Rudolf Byker", email = "rudolfbyker@gmail.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: MIT",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"

[project.urls]
repository = "https://github.com/rudolfbyker/scheduling-util-py"

[project.scripts]
schedule = "scheduling_util._schedule_cli:schedule_cli"

[tool.setuptools_scm]
write_to = "src/scheduling_util/version.py"
